config/routes.rb
Hansode::Application.routes.draw do

  root to: 'dashboard#index'
  resources :estimates do
    resources :items, controller: :estimate_items
  end
  resources :contacts
  resources :clients

  #
  # Authentication Routes
  #
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'signup' => 'users#new', as: :signup
  post 'signup' => 'users#create'
end

app/models/estimate.rb
class Estimate < ActiveRecord::Base
  belongs_to :author, class_name: 'User'
  belongs_to :client
  has_many :items, class_name: 'EstimateItem'
  validates :title, :body, :author, :client, presence: true

  def total
    items.inject(0) { |total, item| total += item.price }
  end
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_filter :set_estimate, only: %w[show edit update destroy]

  def index
    @estimates = Estimate.all
  end

  # GET /estimates/1
  # GET /estimates/1.json
  def show
  end

  # GET /estimates/new
  # GET /estimates/new.json
  def new
    @estimate = Estimate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @estimate }
    end
  end

  # GET /estimates/1/edit
  def edit
  end

  # POST /estimates
  # POST /estimates.json
  def create
    @estimate = Estimate.new(estimate_params)

    respond_to do |format|
      if @estimate.save
        format.html { redirect_to @estimate, notice: 'Estimate was successfully created.' }
        format.json { render json: @estimate, status: :created, location: @estimate }
      else
        format.html { render action: "new" }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /estimates/1
  # PUT /estimates/1.json
  def update
    respond_to do |format|
      if @estimate.update_attributes(estimate_params)
        format.html { redirect_to @estimate, notice: 'Estimate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estimates/1
  # DELETE /estimates/1.json
  def destroy
    @estimate.destroy

    respond_to do |format|
      format.html { redirect_to estimates_url }
      format.json { head :no_content }
    end
  end

  protected
    def estimate_params
      params.require(:estimate).permit(:title, :body, :author_id, :client_id, :published_date, :expiration_date)
    end

    def set_estimate
      @estimate = Estimate.find(params[:id])
    end
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/views/estimates/_form.html.erb
<div class="row-fluid">
<%= form_for(@estimate, builder: Hansode::FormBuilder) do |f| %>
  <% if @estimate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estimate.errors.count, "error") %> prohibited this estimate from being saved:</h2>

      <ul>
      <% @estimate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br />
    <%= f.select :author_id, User.for_select_tag, { include_blank: true } %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br />
    <%= f.select :client_id, Client.for_select_tag, { include_blank: true } %>
  </div>
  <div class="field">
    <%= f.label :published_date %><br />
    <%= f.date_select :published_date %>
  </div>
  <div class="field">
    <%= f.label :expiration_date %><br />
    <%= f.date_select :expiration_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/estimates/edit.html.erb
<h1>Editing estimate</h1>

<%= render 'form' %>

<%= link_to 'Show', @estimate %> |
<%= link_to 'Back', estimates_path %>

app/views/estimates/index.html.erb
<h1>Listing estimates</h1>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Author</th>
    <th>Client</th>
    <th>Published date</th>
    <th>Expiration date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @estimates.each do |estimate| %>
  <tr>
    <td><%= estimate.title %></td>
    <td><%= estimate.body %></td>
    <td><%= estimate.author.email %></td>
    <td><%= link_to estimate.client.name, client_path(estimate.client) %></td>
    <td><%= estimate.published_date %></td>
    <td><%= estimate.expiration_date %></td>
    <td><%= link_to 'Show', estimate %></td>
    <td><%= link_to 'Edit', edit_estimate_path(estimate) %></td>
    <td><%= link_to 'Destroy', estimate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Estimate', new_estimate_path, class: 'btn btn-primary' %>

app/views/estimates/new.html.erb
<h1>New estimate</h1>

<%= render 'form' %>

<%= link_to 'Back', estimates_path %>

app/views/estimates/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @estimate.title %></h1>

<p><%= @estimate.body %></p>

<div ng-controller="EstimateItemsController" ng-init="init(<%= @estimate.id %>)">
  <ol class="estimate-items">
    <li ng-repeat="item in items">
      <input type="text" class="title"
        ng-model="item.title" ng-change="update($event, item)" ng-keydown="keydown($event, $index)">
      <input type="text" class="price"
        ng-model="item.price" ng-change="update($event, item)" ng-keydown="keydown($event, $index)">
    </li>
    <li class="btn btn-success btn-block add" ng-click="add($event)">Add</li>
  </ol>
</div>

<%= link_to 'Edit', edit_estimate_path(@estimate), class: 'btn btn-default' %>
<%= link_to 'Back', estimates_path, class: 'btn btn-default' %>