config/routes.rb
Hansode::Application.routes.draw do

  root to: 'dashboard#index'
  resources :estimates do
    resources :items, controller: :estimate_items
  end
  resources :contacts
  resources :clients

  #
  # Authentication Routes
  #
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'signup' => 'users#new', as: :signup
  post 'signup' => 'users#create'
end

app/models/estimate_item.rb
class EstimateItem < ActiveRecord::Base
  belongs_to :estimate

  validates :estimate, presence: true
end

app/controllers/estimate_items_controller.rb
class EstimateItemsController < ApplicationController
  before_action :set_estimate_item, only: [:show, :edit, :update, :destroy]

  def index
    @estimate_items = EstimateItem.all
  end

  def show
  end

  def new
    @estimate_item = EstimateItem.new
  end

  def edit
  end

  def create
    @estimate_item = EstimateItem.new(estimate_item_params)
    @estimate_item.estimate_id = params[:estimate_id]

    respond_to do |format|
      if @estimate_item.save
        format.json { render 'show' }
        format.html { redirect_to @estimate_item, notice: 'Estimate item was successfully created.' }
      else
        render action: 'new'
      end
    end
  end

  def update
    respond_to do |format|
      if @estimate_item.update(estimate_item_params)
        format.json { render :show }
        format.html { redirect_to @estimate_item, notice: 'Estimate item was successfully updated.' }
      else
        render action: 'edit'
      end
    end
  end

  def destroy
    @estimate_item.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.html { redirect_to estimate_items_url, notice: 'Estimate item was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estimate_item
      @estimate_item = EstimateItem.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def estimate_item_params
      params.require(:estimate_item).permit(:estimate_id, :title, :price, :order)
    end
end

app/helpers/estimate_items_helper.rb
module EstimateItemsHelper
end

app/views/estimate_items/_form.html.erb
<%= form_for(@estimate_item) do |f| %>
  <% if @estimate_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estimate_item.errors.count, "error") %> prohibited this estimate_item from being saved:</h2>

      <ul>
      <% @estimate_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :estimate_id %><br>
    <%= f.number_field :estimate_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estimate_items/edit.html.erb
<h1>Editing estimate_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @estimate_item %> |
<%= link_to 'Back', estimate_items_path %>

app/views/estimate_items/index.html.erb
<h1>Listing estimate_items</h1>

<table>
  <thead>
    <tr>
      <th>Estimate</th>
      <th>Title</th>
      <th>Price</th>
      <th>Order</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @estimate_items.each do |estimate_item| %>
      <tr>
        <td><%= estimate_item.estimate_id %></td>
        <td><%= estimate_item.title %></td>
        <td><%= estimate_item.price %></td>
        <td><%= estimate_item.order %></td>
        <td><%= link_to 'Show', estimate_item %></td>
        <td><%= link_to 'Edit', edit_estimate_item_path(estimate_item) %></td>
        <td><%= link_to 'Destroy', estimate_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estimate item', new_estimate_item_path %>

app/views/estimate_items/new.html.erb
<h1>New estimate_item</h1>

<%= render 'form' %>

<%= link_to 'Back', estimate_items_path %>

app/views/estimate_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Estimate:</strong>
  <%= @estimate_item.estimate_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @estimate_item.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @estimate_item.price %>
</p>

<p>
  <strong>Order:</strong>
  <%= @estimate_item.order %>
</p>

<%= link_to 'Edit', edit_estimate_item_path(@estimate_item) %> |
<%= link_to 'Back', estimate_items_path %>