config/routes.rb
Hansode::Application.routes.draw do

  root to: 'dashboard#index'
  resources :estimates do
    resources :items, controller: :estimate_items
  end
  resources :contacts
  resources :clients

  #
  # Authentication Routes
  #
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'signup' => 'users#new', as: :signup
  post 'signup' => 'users#create'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" ng-app="Hansode">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hansode" %></title>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <header>
      <div class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-global-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_path %>">Hansode</a>
          </div>
          <nav class="collapse navbar-collapse" id="navbar-global-collapse">
            <ul class="nav navbar-nav">
              <li><a href="<%= estimates_path %>">Estimates</a></li>
              <li><a href="<%= clients_path %>">Clients</a></li>
            </ul>
            <ul class="nav navbar-nav pull-right">
              <% if logged_in? %>
                <li><a href="#"><%= current_user.email %></a></li>
                <li><%= link_to 'ログアウト', logout_path, tabindex: '-1' %></li>
              <% else %>
                <li><%= link_to 'Login', login_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>

    <div class="container">
      <% flash.each do |name, message| %>
        <%= content_tag :div, content_tag(:strong, name.capitalize) + ': ' + message, class: "alert #{alert_class(name)}" %>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>

    <footer>
      <div class="container">
        <div class="credit">
          &copy; Hansode Development Team 2014 - <%= link_to 'Hansode', 'http://github.com/niaeashes/hansode', target: '_break' %> licensed under MIT License.
        </div>
        <div class="social-buttons">
          <iframe src="http://ghbtns.com/github-btn.html?user=niaeashes&repo=hansode&type=watch&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="110" height="20"></iframe>
          <iframe src="http://ghbtns.com/github-btn.html?user=niaeashes&repo=hansode&type=fork&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="95" height="20"></iframe>
        </div>
      </div>
    </footer>

  </body>
</html>